In [2]:
import numpy as np
import torch

In [3]:
# 1차원
t = np.array([0., 1., 2., 3., 4., 5., 6.])

In [4]:
print('Rank of t:', t.ndim) #차원 -> 벡터
print('Shape of t:', t.shape) # 1차원, 7개 element

Rank of t: 1
Shape of t: (7,)


In [5]:
#2차원
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank of t:', t.ndim)
print('Shape of t:', t.shape)

Rank of t: 2
Shape of t: (4, 3)


In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [8]:
print(t.dim())
print(t.shape)
print(t.size())
print(t[0], t[1], t[-1]) #element
print(t[2:5], t[4:-1]) #Slicing
print(t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [9]:
t = torch.FloatTensor([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())
print(t.size()) #shape와 동일
print(t[:, 1]) #element
print(t[:,1].size()) #Slicing
print(t[:, :-1])

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [11]:
m1 = torch.FloatTensor([[3,3]])
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)

tensor([[5., 5.]])


In [12]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([3]) # 3-> [[3,3]]
print(m1+m2)

tensor([[4., 5.]])


In [13]:
m1 = torch.FloatTensor([[1,2]])
m2 = torch.FloatTensor([[3], [4]])

#차원의 수를 알아서 맞춰줌

# 원래: 1 2
# 원래: 3
#       4

# 바뀐 후 =============
# 1 2 AND 3 3
# 1 2     4 4 

In [14]:
m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix1:', m1.shape)
print('Shape of Matrix2:', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1,2], [3,4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1:', m1.shape)
print('Shape of Matrix2:', m2.shape)
print(m1.mul(m2))

#matmul과 mul의 차이

#matmul
#행렬 곱 -> 앞 행렬 두 번째랑 뒤 행렬 첫 번째랑 같으면 삭제
# 1 2 matmul 1 (1*1 + 2*2)  5
# 3 4        2 (3*1 + 4*2)  11

#mul
#element 곱 -> 차원 맞춰서 element끼리 곱함
# 1 2 mul 1 1    1 2
# 3 4     2 2    6 8

Shape of Matrix1: torch.Size([2, 2])
Shape of Matrix2: torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1: torch.Size([2, 2])
Shape of Matrix2: torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])


In [15]:
# 평균
t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [16]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t.mean()) #전체 평균
print(t.mean(dim=0)) #열 방향으로 더해서 [2,1]행렬을 만듦 (열 방향을 없애자!)
print(t.mean(dim=1)) #행 방향으로 더해서 [1,2]행렬을 만듦 (행 방향을 없애자!)
print(t.mean(dim=-1))


tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [18]:
# 합
t = torch.FloatTensor([[1,2], [3,4]])
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=1))


tensor(10.)
tensor([4., 6.])
tensor([3., 7.])
tensor([3., 7.])


In [19]:
#Max and Argmax

t = torch.FloatTensor([[1,2], [3,4]])
print(t.max())#전체에서 가장 큰 거
print('Max: ', t.max(dim=0)[0]) #합이 아니라 그 element 중에서 큰 거 찾기
print('ArgMax: ', t.max(dim=0)[1]) #argumax라는 각 인덱스 값까지 같이 return
print(t.max(dim=1))
print(t.max(dim=-1))

tensor(4.)
Max:  tensor([3., 4.])
ArgMax:  tensor([1, 1])
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [20]:
#View (numpy에서는 Reshape)
#짱짱 중요

t = np.array([[[0, 1, 2],
                [3, 4, 5]],
            
              [[6, 7, 8],
               [9, 10, 11]]])

ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [21]:
print(ft.view([-1, 3])) #모르겠을 때 -1 -> 앞은 모르겠고 element 수는 3
print(ft.view([-1, 3]).shape)
# 앞에 2 by 2 가 합쳐짐

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [23]:
print(ft.view([-1, 1, 3]))
print(ft.view([-1, 1, 3]).shape)
#세로가 4

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [25]:
#Squeeze

ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [26]:
print(ft.squeeze())
print(ft.squeeze().shape)

#element가 1이면 없앰

tensor([0., 1., 2.])
torch.Size([3])


In [27]:
#Unsqueeze
#element가 없는 곳에 1을 추가해준다!

ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [28]:
print(ft.unsqueeze(0)) #행방향으로~!
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [30]:
print(ft.unsqueeze(1)) #열방향으로!
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [31]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

#마지막 dim -> dim은 1이 될 거임 (??)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [32]:
#Type Casting

lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [33]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [34]:
bt = torch.ByteTensor([True, False, True, False])
print(bt)

tensor([1, 0, 1, 0], dtype=torch.uint8)


In [35]:
print(bt.long())

tensor([1, 0, 1, 0])


In [36]:
print(bt.float())

tensor([1., 0., 1., 0.])


In [37]:
# Concatencate

x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

print(torch.cat([x,y], dim = 0)) #행방향으로 합침 (쌓는다!)
print(torch.cat([x,y], dim = 1)) #열방향으로 합침

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [40]:
#Stacking

x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])
print(x.size())

print(torch.stack([x, y, z]))
print(torch.stack([x, y, z], dim =1))

torch.Size([2])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [39]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim = 0))
#기본적으로 1 by n 혹은 n by 1은 1이 생략됨 x.size()참고
#여기에 1을 추가해주기 위해 unsqueeze를 사용

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [42]:
print(torch.cat([x, y, z], dim = 0))
print((torch.cat([x, y, z], dim = 0)).size())
#하나의 행렬로 들어가는 게 아니라 1 by 6이 만들어짐

tensor([1., 4., 2., 5., 3., 6.])
torch.Size([6])


In [43]:
#Ones and Zeros

x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [44]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [46]:
#In-place Opreation

x = torch.FloatTensor([[1,2], [3,4]])

print(x.mul(2.)) # -> x * 2
print(x)
print(x.mul_(2.)) #새로운 메모리 할당 x 기존 x에 할당해라
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
