In [1]:
import numpy as np
import torch

In [2]:
# Numpy Review: 1D Array Numpy
t = np.array([0., 1., 2., 3., 4., 5., 6.])
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim) #몇 개의 차원?
print('Shape of t: ', t.shape) #몇 개가 들어가 있니?

Rank of t:  1
Shape of t:  (7,)


In [5]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])
print('t[:2] t[3:]     = ', t[:2], t[3:])

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


In [6]:
# Numpy Review: 2D Array with Numpy
t = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(t)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [8]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape) #(세로, 가로)

Rank of t:  2
Shape of t:  (4, 3)


In [10]:
# Pytorch: 1D Array with PyTorch
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t)

tensor([0., 1., 2., 3., 4., 5., 6.])


In [12]:
print(t.dim()) # 차원
print(t.shape) # shape
print(t.size()) # 전체 개수
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])
print('t[:2] t[3:]     = ', t[:2], t[3:])

1
torch.Size([7])
torch.Size([7])
t[0] t[1] t[-1] =  tensor(0.) tensor(1.) tensor(6.)
t[2:5] t[4:-1]  =  tensor([2., 3., 4.]) tensor([4., 5.])
t[:2] t[3:]     =  tensor([0., 1.]) tensor([3., 4., 5., 6.])


In [13]:
# Pytorch: 2D Array with Pytorch
t = torch.FloatTensor([[1., 2., 3.], 
                       [4., 5., 6.], 
                       [7., 8., 9.], 
                       [10., 11., 12]])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [14]:
print(t.dim()) # 차원
print(t.shape) # shape
print(t.size()) # 전체 개수
print(t[:, 1]) # 첫 번째 차원-세로-에서는 다 가져오되, 두 번째 차원-가로-에서는 두 번째 element!
print(t[:, 1].size())
print(t[:, :-1])

2
torch.Size([4, 3])
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [16]:
#Broadcasting: Same Shape
m1 = torch.FloatTensor([[3,3]]) # shape = (1,2)
m2 = torch.FloatTensor([[2,2]])
print(m1+m2)
print(m1)

tensor([[5., 5.]])
tensor([[3., 3.]])


In [18]:
#Broadcasting: Vector + Scalar
m1 = torch.FloatTensor([[1,2]]) # shape = (1,2)
m2 = torch.FloatTensor([3]) # shape = (1,) vector -> (1,2) [[3,3]]
print(m1 + m2)

tensor([[4., 5.]])


In [19]:
#Broadcasting: 2*1 Vector + 1*2 Vector
m1 = torch.FloatTensor([[1,2]]) # shape = (1,2) -> (2,2)
m2 = torch.FloatTensor([[3], [4]]) # shape = (2,1) -> (2,2) => 같은 크기로 맞춰주기!
print(m1 + m2)

tensor([[4., 5.],
        [5., 6.]])


In [21]:
print('-------------')
print('Mul vs Matmul')
print('-------------')

m1 = torch.FloatTensor([[1,2], [3,4]]) #(2,2)
m2 = torch.FloatTensor([[1], [2]]) #(2,1) -> 행렬곱은 사이즈 안 맞추고 그냥!

print('shape of matrix 1: ', m1.shape)
print('shape of matrix 2: ', m2.shape)
print(m1.matmul(m2))

m1 = torch.FloatTensor([[1,2], [3,4]]) #(2,2)
m2 = torch.FloatTensor([[1], [2]]) #(2,1) -> (2,2)

print('shape of matrix 1: ', m1.shape)
print('shape of matrix 2: ', m2.shape)
print(m1.mul(m2)) 

-------------
Mul vs Matmul
-------------
shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
shape of matrix 1:  torch.Size([2, 2])
shape of matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])


In [22]:
# Mean & Sum

t = torch.FloatTensor([1,2])
print(t.mean())

tensor(1.5000)


In [23]:
t = torch.LongTensor([1,2])
try:
  print(t.mean())
except Exception as exc:
  print(exc)

mean(): input dtype should be either floating point or complex dtypes. Got Long instead.


In [24]:
t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [26]:
print(t.mean())
print(t.mean(dim=0)) #행방향
print(t.mean(dim=1)) #열방향
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [27]:
# Max and Argmax(인덱스값)

t = torch.FloatTensor([[1,2], [3,4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [28]:
print(t.max())

tensor(4.)


In [29]:
print(t.max(dim=0))
print('Max: ', t.max(dim=0)[0])
print('Argmax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
Argmax:  tensor([1, 1])


In [30]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


In [32]:
# View = Reshape

t = np.array([[[0,1,2],
               [3,4,5]],
              [[6,7,8],
              [9,10,11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [34]:
print(ft.view([-1,3])) # -1 = 모르겠어~
print(ft.view([-1,3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [35]:
print(ft.view([-1,1,3]))
print(ft.view([-1,1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


In [36]:
# Squeeze
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [37]:
print(ft.squeeze())
print(ft.squeeze().shape) # shape: (3,1) -> (3,) 1인 dim을 없애줌

tensor([0., 1., 2.])
torch.Size([3])


In [46]:
# Unsqueeze
ft = torch.FloatTensor([0,1,2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [47]:
print(ft.unsqueeze(0)) # 첫번째 dim에 1을 넣어
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [48]:
print(ft.view(1,-1))
print(ft.view(1,-1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [49]:
print(ft.unsqueeze(-1)) # dim = -1 -> 마지막 dimension
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [50]:
# Type Casting
lt = torch.LongTensor([1,2,3,4])
print(lt)

tensor([1, 2, 3, 4])


In [51]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [52]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [53]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


In [54]:
# Concatenate

x = torch.FloatTensor([[1,2], [3,4]])
y = torch.FloatTensor([[5,6], [7,8]])

In [55]:
print(torch.cat([x,y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [56]:
# Stacking

x = torch.FloatTensor([1,4])
y = torch.FloatTensor([2,5])
z = torch.FloatTensor([3,6])

In [60]:
print(torch.stack([x,y,z]))
print(torch.stack([x,y,z], dim=1))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [61]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [62]:
# Ones and Zeros

x = torch.FloatTensor([[0,1,2], [2,1,0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [63]:
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [64]:
# In-place Operation
x = torch.FloatTensor([[1,2], [3,4]])

In [66]:
print(x.mul(2.))
print(x)
print(x.mul_(2.)) #_: 메모리 새로 쓰지말고 기존에 있던 거에 넣어라!
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
